version: '3.8'
services:
  nginx:
    build: ./client
    ports:
      - "8070:8080"
    volumes:
      - ./client/src:/var/www/html
  
  app:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "9229:9229"
    command: npm run debug

  admin:
    image: mongo-express:1.0.0-alpha
    ports:
      - "8071:8081"

volumes:
  node_modules: