version: '3.8'
services:
  nginx:
    image: ghcr.io/natsu09coder/no-game-frontend
    
  app:
    image: ghcr.io/natsu09coder/no-game-backend
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - NODE_PORT=9090
      - ADMIN_CODE

  mongo:
    image: mongo:4.4.22-focal  # MongoDB 5.0+ requires a CPU with AVX support. Does not run in production!
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: